{% set name = "libssh" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.libssh.org/files/0.10/{{ name }}-{{ version }}.tar.xz
  sha256: 07392c54ab61476288d1c1f0a7c557b50211797ad00c34c3af2bbc4dbc4bd97d

build:
  number: 1
  skip: true  # [not unix]
  run_exports:
    # We pin to a minor version due to an incompatibility 
    # between 0.8 and 0.10
    # https://abi-laboratory.pro/index.php?view=timeline&l=libssh
    - {{ pin_subpackage('libssh', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - openssl
    - zlib

test:
  commands:
    - test -f $PREFIX/include/libssh/libssh.h
    - test -f $PREFIX/lib/pkgconfig/libssh.pc
    - test -f $PREFIX/lib/libssh$SHLIB_EXT

about:
  home: https://libssh.org
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: libssh - The SSH library

  description: |
    libssh is a multiplatform C library implementing the SSHv2 protocol
    on client and server side. With libssh, you can remotely execute
    programs, transfer files, use a secure and transparent tunnel,
    manage public keys and much more ...
  doc_url: https://www.libssh.org/documentation/
  dev_url: https://www.libssh.org/communication/

extra:
  recipe-maintainers:
    - jan-janssen
    - matthiasdiener
