{% set name = "libssh" %}
{% set version = "0.8.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.libssh.org/files/0.8/{{ name }}-{{ version }}.tar.xz
  sha256: 8559e19da0c40b6f93482b6160219ad77a4d9f1dc190bf174757455c6ae26825

build:
  number: 0
  skip: true  # [not unix]
  run_exports:
    - {{ pin_subpackage('libssh') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
  host:
    - openssl
    - zlib

test:
  commands:
    - conda inspect linkages {{ name }}  # [linux]

about:
  home: https://libssh.org
  license: LGPL-2.1
  license_family: GPL
  license_file: COPYING
  summary: libssh - The SSH library

  description: |
    libssh is a multiplatform C library implementing the SSHv2 protocol 
    on client and server side. With libssh, you can remotely execute 
    programs, transfer files, use a secure and transparent tunnel, 
    manage public keys and much more ...  
  doc_url: https://www.libssh.org/documentation/
  dev_url: https://www.libssh.org/communication/

extra:
  recipe-maintainers:
    - jan-janssen
