{% set name = "libssh" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.libssh.org/files/0.9/{{ name }}-{{ version }}.tar.xz
  sha256: 86bcf885bd9b80466fe0e05453c58b877df61afa8ba947a58c356d7f0fab829b

build:
  number: 0
  skip: true  # [not unix]
  run_exports:
    - {{ pin_subpackage('libssh') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - openssl
    - zlib

test:
  commands:

about:
  home: https://libssh.org
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: libssh - The SSH library

  description: |
    libssh is a multiplatform C library implementing the SSHv2 protocol
    on client and server side. With libssh, you can remotely execute
    programs, transfer files, use a secure and transparent tunnel,
    manage public keys and much more ...
  doc_url: https://www.libssh.org/documentation/
  dev_url: https://www.libssh.org/communication/

extra:
  recipe-maintainers:
    - jan-janssen
    - matthiasdiener
