{% set name = "libssh" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.libssh.org/files/0.10/{{ name }}-{{ version }}.tar.xz
  sha256: 15b83d7b74c8c67f758fb32faf1d9a35d5f8f50db523276a419e9876530f098a

build:
  number: 0
  skip: true  # [not unix]
  run_exports:
    - {{ pin_subpackage('libssh') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - openssl
    - zlib

test:
  commands:
    - test -f $PREFIX/include/libssh/libssh.h
    - test -f $PREFIX/lib/pkgconfig/libssh.pc
    - test -f $PREFIX/lib/libssh$SHLIB_EXT

about:
  home: https://libssh.org
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: libssh - The SSH library

  description: |
    libssh is a multiplatform C library implementing the SSHv2 protocol
    on client and server side. With libssh, you can remotely execute
    programs, transfer files, use a secure and transparent tunnel,
    manage public keys and much more ...
  doc_url: https://www.libssh.org/documentation/
  dev_url: https://www.libssh.org/communication/

extra:
  recipe-maintainers:
    - jan-janssen
    - matthiasdiener
