schema_version: 1

context:
  name: libssh
  version: "0.11.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://www.libssh.org/files/${{ (version | split("."))[:2] | join(".") }}/${{ name }}-${{ version }}.tar.xz
  sha256: 69529fc18f5b601f0baf0e5a4501a2bc26df5e2f116f5f8f07f19fafaa6d04e7

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cmake
    - make
  host:
    - openssl
    - zlib
    - krb5
  run_exports:
    # We pin to a minor version due to an incompatibility 
    # between 0.8 and 0.10
    # https://abi-laboratory.pro/index.php?view=timeline&l=libssh
    - ${{ pin_subpackage('libssh', upper_bound='x.x') }}

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/include/libssh/libssh.h
          - test -f $PREFIX/lib/pkgconfig/libssh.pc
          - test -f $PREFIX/lib/libssh$SHLIB_EXT
        else:
          - if not exist %LIBRARY_INC%\libssh\libssh.h exit 1
          - if not exist %LIBRARY_LIB%\libssh.lib exit 1 
          - if not exist %LIBRARY_BIN%\libssh.dll exit 1

about:
  homepage: https://libssh.org
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: libssh - The SSH library

  description: |
    libssh is a multiplatform C library implementing the SSHv2 protocol
    on client and server side. With libssh, you can remotely execute
    programs, transfer files, use a secure and transparent tunnel,
    manage public keys and much more ...
  documentation: https://www.libssh.org/documentation/

extra:
  recipe-maintainers:
    - jan-janssen
    - matthiasdiener
