travis:
  secure:
    BINSTAR_TOKEN: Xvn1N2bAC8aEnLzHTqSbrllQbWDXZuUlF5CPD4pKthxJoN0+uF9XS2NjaluahHNZy12c+CNmIFs6D4WyPxAGNEr6KX4TLT/hYi6D+81+1a169dSdZblBkxiZfHKxSCRBQIw9XvBuzvp8vonFIN5WvZ7rO1OoJ6OOwMvQOQaQl7K1HWhh9E3qxuk64gdplrzFvYcF7e4L0DbxU8y2rPfcS7+qqgHLessZnYVFAYbC458N+h68G7swVTcQesmwGbIl/3d8TwrckoHnsHPHMFllorFQabVJWygJFi+k0T4nGD0Tv+sNNpKlTXTX2Y3Sk7BQ/+en2a/Juu6ZSLKfldpcoGMLaImd7RhK8eZ/ajt/bmo01p9IBM3sEMqJ3ZuGDCcS+ePIMH6nOuclsLRvT9nuxlfeFQ+Ja+SrxdC+dJ+4wLniPUSr+dqT/Em1fI9j6pay9cStjxv8s+G3jp7YkloTvLzaI9Py/43xU43LO0hlWsFr2jE2lv6XhmCTIjPTlTVlggSqpagt75/ZDy2EZnnWcnC5yy06r+uIXLXk+2EejnZkbkJpHFhSvcYguZUv2KsDh3EWrB6r3oRA9NebHuIPEWkK3QfhRKRfALNOUJnCSMOTFFMZvje4wcP1x62VOfFrbBfenTE29xQQ6X7aVKQhg5hVlBpQZZWz9+p7xrmjBlE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
